import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createServerClient } from '@/lib/supabase'
import SiteNav from '@/components/SiteNav'
import BgCanvas from '@/components/BgCanvas'

interface Profile {
  id: string
  username: string | null
  first_name: string | null
  last_name: string | null
}

interface Build {
  id: string
  title: string
  budget: string | null
  use_case: string | null
  created_at: string
  vote_score: number
  comment_count: number
}

async function fetchProfile(username: string): Promise<Profile | null> {
  const supabase = createServerClient()
  const { data } = await supabase
    .from('profiles')
    .select('id, username, first_name, last_name')
    .eq('username', username.toLowerCase())
    .single()
  return data ?? null
}

async function fetchUserBuilds(userId: string): Promise<Build[]> {
  const supabase = createServerClient()
  const { data } = await supabase
    .from('builds')
    .select('id, title, budget, use_case, created_at, vote_score, comment_count')
    .eq('user_id', userId)
    .order('created_at', { ascending: false })
    .limit(50)
  return (data ?? []) as Build[]
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ username: string }>
}): Promise<Metadata> {
  const { username } = await params
  const profile = await fetchProfile(username)
  if (!profile) return { title: 'User Not Found · Zuuke' }
  const name = profile.first_name ? `${profile.first_name}${profile.last_name ? ' ' + profile.last_name : ''}` : `@${username}`
  return {
    title: `${name}'s Builds · Zuuke`,
    description: `PC builds generated by ${name} on Zuuke AI.`,
    alternates: { canonical: `https://zuuke.shop/u/${username}` },
    openGraph: {
      title: `${name}'s Builds · Zuuke`,
      description: `PC builds generated by ${name} on Zuuke AI.`,
    },
  }
}

function timeAgo(iso: string): string {
  const s = Math.floor((Date.now() - new Date(iso).getTime()) / 1000)
  if (s < 86400) return `${Math.floor(s / 3600)}h ago`
  if (s < 2592000) return `${Math.floor(s / 86400)}d ago`
  return new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

export default async function UserProfilePage({
  params,
}: {
  params: Promise<{ username: string }>
}) {
  const { username } = await params
  const profile = await fetchProfile(username)
  if (!profile) notFound()

  const builds = await fetchUserBuilds(profile.id)
  const totalVotes = builds.reduce((sum, b) => sum + (b.vote_score ?? 0), 0)
  const displayName = profile.first_name
    ? `${profile.first_name}${profile.last_name ? ' ' + profile.last_name : ''}`
    : `@${profile.username}`

  const initial = (profile.first_name ?? profile.username ?? 'A')[0].toUpperCase()

  return (
    <>
      <BgCanvas opacity={0.2} particleCount={50} connectDistance={90} />
      <SiteNav />

      <div className="page" style={{ position: 'relative', zIndex: 1, paddingTop: 100 }}>
        <div className="profile-wrap">

          {/* Profile header */}
          <div className="profile-header">
            <div className="profile-avatar">{initial}</div>
            <div className="profile-info">
              <h1 className="profile-name">{displayName}</h1>
              {profile.username && (
                <p className="profile-username">@{profile.username}</p>
              )}
              <div className="profile-stats">
                <span><strong>{builds.length}</strong> builds</span>
                <span><strong>{totalVotes}</strong> points</span>
              </div>
            </div>
          </div>

          {/* Builds list */}
          <div className="profile-builds-header">
            <h2 className="profile-section-title">BUILDS</h2>
          </div>

          {builds.length === 0 ? (
            <div className="profile-empty">
              <p>No builds shared yet.</p>
              <Link href="/chat" className="btn-secondary" style={{ marginTop: 20 }}>
                Generate a build →
              </Link>
            </div>
          ) : (
            <div className="profile-build-list">
              {builds.map(b => (
                <Link key={b.id} href={`/build/${b.id}`} className="profile-build-item">
                  <div className="profile-build-top">
                    <span className="profile-build-title">{b.title}</span>
                    {b.budget && <span className="build-budget-badge" style={{ fontSize: 10 }}>{b.budget}</span>}
                  </div>
                  {b.use_case && (
                    <p className="profile-build-prompt">
                      {b.use_case.length > 100 ? b.use_case.slice(0, 100) + '…' : b.use_case}
                    </p>
                  )}
                  <div className="profile-build-meta">
                    <span>
                      <svg width="11" height="11" viewBox="0 0 24 24" fill="currentColor" style={{ marginRight: 3 }}>
                        <path d="M12 4l8 8H4l8-8z"/>
                      </svg>
                      {b.vote_score ?? 0} points
                    </span>
                    <span>
                      <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ marginRight: 3 }}>
                        <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
                      </svg>
                      {b.comment_count ?? 0} comments
                    </span>
                    <span>{timeAgo(b.created_at)}</span>
                  </div>
                </Link>
              ))}
            </div>
          )}

        </div>
      </div>

      <footer style={{ position: 'relative', zIndex: 1 }}>
        <div className="footer-logo">ZUUKE<span>.</span></div>
        <div className="footer-text">© 2026 Zuuke AI · All rights reserved</div>
        <div className="footer-links">
          <Link href="/about">About Us</Link>
          <Link href="/privacy">Privacy</Link>
          <Link href="/terms">Terms</Link>
          <Link href="/affiliate">Affiliate Disclosure</Link>
        </div>
      </footer>
    </>
  )
}
