'use client'

import { useEffect, useRef } from 'react'
import Link from 'next/link'
import BgCanvas from '@/components/BgCanvas'

export default function TermsPage() {
  const navRef = useRef<HTMLElement>(null)

  useEffect(() => {
    const onScroll = () => navRef.current?.classList.toggle('scrolled', window.scrollY > 40)
    window.addEventListener('scroll', onScroll)
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  return (
    <>
      <BgCanvas opacity={0.3} particleCount={60} connectDistance={100} />

      <nav ref={navRef} className="nav">
        <Link href="/" className="nav-logo" onClick={() => setTimeout(() => window.scrollTo({ top: 0, behavior: 'smooth' }), 50)}>
          <div className="nav-logo-mark">
            <img src="/zuukelogo-sq.png" style={{width:38,height:38,objectFit:"cover"}} alt="Zuuke logo"/>
          </div>
          <span className="nav-wordmark">ZUUKE<span>.</span></span>
        </Link>
        <div className="nav-links">
          <Link href="/#how-it-works">How It Works</Link>
          <Link href="/#features">Features</Link>
          <Link href="/#pricing">Pricing</Link>
          <Link href="/about">About Us</Link>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Link href="/auth?mode=login" className="nav-login">Log In</Link>
          <Link href="/chat" className="nav-cta"><span>Start Building →</span></Link>
        </div>
      </nav>

      <div className="page" style={{ position: 'relative', zIndex: 1, paddingTop: 100 }}>
        <section style={{ maxWidth: 760, margin: '0 auto', padding: '60px 24px 100px' }}>

          <div className="section-label" style={{ marginBottom: 16 }}>Legal</div>
          <h1 style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(42px, 6vw, 72px)', letterSpacing: '0.04em', lineHeight: 1, marginBottom: 12 }}>
            TERMS &amp;<br /><span style={{ color: 'var(--orange)' }}>CONDITIONS</span>
          </h1>
          <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--mist)', letterSpacing: '0.1em', marginBottom: 56, textTransform: 'uppercase' }}>
            Last updated: May 2026 · Effective immediately
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 48 }}>

            <LegalSection title="01 — Acceptance of Terms">
              <p>By accessing or using Zuuke (&quot;the Service&quot;) at zuuke.shop, you agree to be bound by these Terms and Conditions (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.</p>
              <p>These Terms apply to all visitors, users, and subscribers. We reserve the right to update these Terms at any time. Continued use of the Service after changes constitutes acceptance.</p>
            </LegalSection>

            <LegalSection title="02 — Description of Service">
              <p>Zuuke is an AI-powered PC build recommendation tool. Users describe their budget and intended use case, and Zuuke generates personalized PC component recommendations using artificial intelligence.</p>
              <p>Zuuke offers:</p>
              <ul>
                <li><strong>Free Tier</strong> — Up to 10 AI messages per day, no account required for guest access (5 messages)</li>
                <li><strong>Pro Plan</strong> — Unlimited messages for $5.00 USD per month, billed monthly via Stripe</li>
              </ul>
            </LegalSection>

            <LegalSection title="03 — AI Disclaimer">
              <p>Zuuke&apos;s recommendations are generated by artificial intelligence and are provided for <strong>informational and educational purposes only</strong>. They do not constitute professional advice.</p>
              <p>While we strive for accuracy, AI-generated content may contain errors, outdated pricing, discontinued products, or compatibility mistakes. You are solely responsible for:</p>
              <ul>
                <li>Verifying all component compatibility before purchasing</li>
                <li>Confirming current pricing from retailers</li>
                <li>Ensuring parts meet your specific requirements</li>
                <li>Any purchasing decisions made based on our recommendations</li>
              </ul>
              <p>Zuuke is not liable for any direct or indirect damages resulting from purchases made based on our AI-generated recommendations.</p>
            </LegalSection>

            <LegalSection title="04 — User Accounts">
              <p>To access features beyond guest access, you must create an account with a valid email address. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.</p>
              <p>You must be at least 13 years old to create an account. By creating an account, you represent that you meet this age requirement.</p>
              <p>We reserve the right to suspend or terminate accounts that violate these Terms, engage in abusive behavior, or attempt to circumvent usage limits.</p>
            </LegalSection>

            <LegalSection title="05 — Subscriptions and Billing">
              <p>Zuuke Pro is a monthly subscription at $5.00 USD per month. Subscriptions are billed in advance on a monthly basis through Stripe.</p>
              <ul>
                <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No refunds are issued for partial months.</li>
                <li><strong>Renewals:</strong> Subscriptions automatically renew each month unless cancelled before the renewal date.</li>
                <li><strong>Price Changes:</strong> We reserve the right to modify subscription pricing with 30 days&apos; notice. Continued use after a price change constitutes acceptance.</li>
                <li><strong>Failed Payments:</strong> If a payment fails, access to Pro features may be suspended until payment is resolved.</li>
              </ul>
            </LegalSection>

            <LegalSection title="06 — Acceptable Use">
              <p>You agree not to use Zuuke to:</p>
              <ul>
                <li>Attempt to circumvent free tier message limits through automation, bots, or multiple accounts</li>
                <li>Scrape, copy, or reproduce our service for commercial use</li>
                <li>Interfere with or disrupt the service or servers</li>
                <li>Use the service for any unlawful purpose</li>
                <li>Reverse engineer or attempt to extract our AI prompts or system architecture</li>
              </ul>
              <p>Violation of acceptable use policies may result in immediate account termination without refund.</p>
            </LegalSection>

            <LegalSection title="07 — Affiliate Links">
              <p>Zuuke participates in the Amazon Associates affiliate program. Product links provided in build recommendations may be affiliate links. When you click these links and make a purchase, we may earn a small commission at no additional cost to you.</p>
              <p>Affiliate commissions do not influence our recommendations. See our full <Link href="/affiliate" style={{ color: 'var(--cyan)' }}>Affiliate Disclosure</Link> for details.</p>
            </LegalSection>

            <LegalSection title="08 — Intellectual Property">
              <p>The Zuuke name, logo, website design, and underlying software are the intellectual property of Zuuke AI. You may not copy, reproduce, or use these without written permission.</p>
              <p>AI-generated recommendations are provided for your personal use. You may share specific build recommendations but may not republish or sell Zuuke-generated content commercially.</p>
            </LegalSection>

            <LegalSection title="09 — Limitation of Liability">
              <p>To the maximum extent permitted by law, Zuuke AI and its founders shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to:</p>
              <ul>
                <li>Losses arising from purchases made based on our recommendations</li>
                <li>Service downtime or interruptions</li>
                <li>Data loss or unauthorized access</li>
                <li>Any errors or omissions in AI-generated content</li>
              </ul>
              <p>Our total liability to you for any claim shall not exceed the amount you paid us in the 12 months preceding the claim.</p>
            </LegalSection>

            <LegalSection title="10 — Disclaimer of Warranties">
              <p>The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or that AI recommendations will be accurate or suitable for your needs.</p>
            </LegalSection>

            <LegalSection title="11 — Governing Law">
              <p>These Terms are governed by and construed in accordance with the laws of the State of Florida, United States, without regard to its conflict of law provisions. Any disputes shall be resolved in the courts of Miami-Dade County, Florida.</p>
            </LegalSection>

            <LegalSection title="12 — Contact">
              <p>For questions about these Terms, contact us:</p>
              <ul>
                <li>Email: <a href="mailto:legal@zuuke.shop" style={{ color: 'var(--cyan)' }}>legal@zuuke.shop</a></li>
                <li>Website: <Link href="/" style={{ color: 'var(--cyan)' }}>zuuke.shop</Link></li>
              </ul>
            </LegalSection>

          </div>
        </section>
      </div>

      <footer style={{ position: 'relative', zIndex: 1 }}>
        <div className="footer-logo">ZUUKE<span>.</span></div>
        <div className="footer-text">© 2026 Zuuke AI · All rights reserved</div>
        <div className="footer-links">
          <Link href="/about">About Us</Link>
          <Link href="/privacy">Privacy</Link>
          <Link href="/terms">Terms</Link>
          <Link href="/affiliate">Affiliate Disclosure</Link>
        </div>
      </footer>
    </>
  )
}

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ borderTop: '1px solid var(--border)', paddingTop: 32 }}>
      <h2 style={{ fontFamily: 'var(--font-display)', fontSize: 22, letterSpacing: '0.06em', color: 'var(--cyan)', marginBottom: 20 }}>
        {title}
      </h2>
      <div style={{
        display: 'flex', flexDirection: 'column', gap: 14,
        fontFamily: 'var(--font-body)', fontSize: 15, lineHeight: 1.75,
        color: 'var(--mist-2)', fontWeight: 400,
      }}>
        {children}
      </div>
    </div>
  )
}
